<?xml version="1.0" encoding="utf-8"?><Database Name="QLDSV" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=QLDSV;Integrated Security=True" SettingsObjectName="QLDSV.Properties.Settings" SettingsPropertyName="QLDSVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HOCPHAN" Member="HOCPHANs">
    <Type Name="HOCPHAN">
      <Column Name="MAHP" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENHP" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TINCHI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HOCKY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MAKHOA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PHANTRAMQT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOCPHAN_KETQUA" Member="KETQUAs" ThisKey="MAHP" OtherKey="MAHP" Type="KETQUA" />
      <Association Name="KHOA_HOCPHAN" Member="KHOA" ThisKey="MAKHOA" OtherKey="MAKHOA" Type="KHOA" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.KETQUA" Member="KETQUAs">
    <Type Name="KETQUA">
      <Column Name="MASV" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAHP" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DIEMQT" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DIEMTHI" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DIEMTK" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="KQ" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="HOCPHAN_KETQUA" Member="HOCPHAN" ThisKey="MAHP" OtherKey="MAHP" Type="HOCPHAN" IsForeignKey="true" />
      <Association Name="SINHVIEN_KETQUA" Member="SINHVIEN" ThisKey="MASV" OtherKey="MASV" Type="SINHVIEN" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHOA" Member="KHOAs">
    <Type Name="KHOA">
      <Column Name="MAKHOA" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKHOA" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NAMTHANHLAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KHOA_HOCPHAN" Member="HOCPHANs" ThisKey="MAKHOA" OtherKey="MAKHOA" Type="HOCPHAN" />
      <Association Name="KHOA_LOP" Member="LOPs" ThisKey="MAKHOA" OtherKey="MAKHOA" Type="LOP" />
    </Type>
  </Table>
  <Table Name="dbo.LOP" Member="LOPs">
    <Type Name="LOP">
      <Column Name="MALOP" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOP" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SISO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MAKHOA" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="LOP_SINHVIEN" Member="SINHVIENs" ThisKey="MALOP" OtherKey="MALOP" Type="SINHVIEN" />
      <Association Name="KHOA_LOP" Member="KHOA" ThisKey="MAKHOA" OtherKey="MAKHOA" Type="KHOA" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.SINHVIEN" Member="SINHVIENs">
    <Type Name="SINHVIEN">
      <Column Name="MASV" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MALOP" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="SINHVIEN_KETQUA" Member="KETQUAs" ThisKey="MASV" OtherKey="MASV" Type="KETQUA" />
      <Association Name="LOP_SINHVIEN" Member="LOP" ThisKey="MALOP" OtherKey="MALOP" Type="LOP" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="TenTN" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pass" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="rights" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>